#!/bin/bash

#
# banfromlog: examines logs to prevent attacks and forbids ips who tries to do
#             nasty things.
# invaliduser: This plugin just show the attemps to login with an invalid
#              user. It doesn't take any action.
# Copyright (C) 2005 Jose Sanchez (Original version) <jose_at_serhost_dot_com>
# Copytight (C) 2009 Mateo Matachana (Current version) <mat30.mail gmail.com>

# Specials thanks to: Julio Mendoza
# julio_dot_mendoza_at_eemsystems_dot_com  - http://eemsystems.com/
# who suggest the sqlite compatibility and programmed almost all sqlite compatibility

# This script was based on another one from: http://tuxworld.homelinux.org
# In this version you hardly can find a line from them.

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

LOGFILE="/var/log/auth.log"

if [ "$1" == "install-db" ]; then
exit 0;
fi

cat $LOGFILE|grep Invalid|awk '{print $10}'|sort -n|uniq
