#!/bin/bash

#
# banfromlog: examines logs to prevent attacks and forbids ips who tries to do
#             nasty things.
# dfindban: bans the DFInd port scanner.
# Copyright (C) 2009 Mateo Matachana (Current version) <mat30.mail gmail.com>

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

LOGFILE="/var/log/httpd/error_log"

. "$LIBDIR/database.api"

if [ "$1" == "install-db" ]; then
echo "Creating DB..."
bfl_db_execute_query "CREATE TABLE IF NOT EXISTS blacklist (ip varchar(50) NOT NULL unique,comment varchar(250));";
bfl_db_execute_query "CREATE TABLE IF NOT EXISTS invalid_report (ip varchar(50) NOT NULL unique);";
exit 0;
fi


db_exist=`bfl_db_execute_query "SELECT ip FROM blacklist "`;

echo
echo "Logging..."
echo
o=0

datum=`date`

for i in `cat $LOGFILE|grep "w00tw00t.at.ISC.SANS.DFind" | awk '{print $8}' | sed 's/]//' | sort -n | uniq`
do
		search=`echo $db_exist | grep "$i" |  awk 'BEGIN{ FS=" " }; { print $1 }' `;
		if [ ! $search ]; then
			bfl_db_execute_query "INSERT INTO blacklist ( ip, comment ) VALUES ( '$i', 'dfind, $datum ')";
			bfl_db_execute_query "INSERT INTO invalid_report VALUES('$i')";
			echo "Logging: $i"
			((o=o+1))
		fi
		db_exist="$db_exist $i";
		
done

echo "Finished. Added $o new ip(s) to the firewall"
echo

